export interface FormData {
  fullName: string;
  birthDate: string;
  bsn: string;
  address: string;
  email: string;
  phone: string;
  hasPartner: string;
  partnerName: string;
  partnerBirthDate: string;
  partnerBsn: string;
  hasChildren: string;
  childrenCount: string;
  childrenNames: string;
  childrenBirthDates: string;
  childrenBsns: string;
  livedInNL: string;
  nlPeriod: string;
  has30PercentRuling: string;
  rulingFor: string;
  rulingPeriod: string;
  partialTaxLiability: string;
  hasEmploymentIncome: string;
  employerNames: string;
  employerCountries: string;
  employerWorkLocations: string;
  employerPeriods: string;
  partnerEmployerNames: string;
  partnerEmployerCountries: string;
  partnerEmployerWorkLocations: string;
  partnerEmployerPeriods: string;
  hasCommuteExpenses: string;
  hasBusinessIncome: string;
  businessNames: string;
  businessLegalForms: string;
  businessKvkNumbers: string;
  businessStartDates: string;
  businessHours1225: string;
  selfEmployedDeductionHistory: string;
  wasNotEntrepreneur: string;
  hadStartupYears: string;
  aovPremium: string;
  businessSpecialItems: string;
  partnerBusinessNames: string;
  partnerBusinessLegalForms: string;
  partnerBusinessKvkNumbers: string;
  partnerBusinessStartDates: string;
  partnerBusinessHours1225: string;
  partnerSelfEmployedDeductionHistory: string;
  partnerWasNotEntrepreneur: string;
  partnerHadStartupYears: string;
  partnerAovPremium: string;
  partnerBusinessSpecialItems: string;
  hasFreelanceIncome: string;
  freelanceDetails: string;
  partnerFreelanceDetails: string;
  hasSocialBenefits: string;
  benefitsDetails: string;
  partnerBenefitsDetails: string;
  hasPensionIncome: string;
  pensionDetails: string;
  pensionStartedIn2024: string;
  partnerPensionDetails: string;
  partnerPensionStartedIn2024: string;
  receivesAlimony: string;
  alimonyAmount: string;
  partnerAlimonyAmount: string;
  hasSubstantialInterest: string;
  dividendReceived: string;
  sharesSold: string;
  partnerDividendReceived: string;
  partnerSharesSold: string;
  hasAssets: string;
  savingsBalance: string;
  investments: string;
  realEstate: string;
  otherAssets: string;
  debts: string;
  partnerSavingsBalance: string;
  partnerInvestments: string;
  partnerRealEstate: string;
  partnerOtherAssets: string;
  partnerDebts: string;
  hasOwnHome: string;
  homeAddress: string;
  homeWozValue: string;
  homeMortgageInterest: string;
  homeBoughtOrSold: string;
  partnerHomeAddress: string;
  partnerHomeWozValue: string;
  partnerHomeMortgageInterest: string;
  partnerHomeBoughtOrSold: string;
  mortgageDistribution: string;
  alimonyPaid: string;
  partnerAlimonyPaid: string;
  medicalExpenses: string;
  partnerMedicalExpenses: string;
  donations: string;
  partnerDonations: string;
  annuityPremiums: string;
  partnerAnnuityPremiums: string;
  otherDeductions: string;
  partnerOtherDeductions: string;
  provisionalAssessment: string;
  partnerProvisionalAssessment: string;
  additionalRemarks: string;
  truthfulDeclaration: string;
}

export const initialFormData: FormData = {
  fullName: '',
  birthDate: '',
  bsn: '',
  address: '',
  email: '',
  phone: '',
  hasPartner: '',
  partnerName: '',
  partnerBirthDate: '',
  partnerBsn: '',
  hasChildren: '',
  childrenCount: '',
  childrenNames: '',
  childrenBirthDates: '',
  childrenBsns: '',
  livedInNL: '',
  nlPeriod: '',
  has30PercentRuling: '',
  rulingFor: '',
  rulingPeriod: '',
  partialTaxLiability: '',
  hasEmploymentIncome: '',
  employerNames: '',
  employerCountries: '',
  employerWorkLocations: '',
  employerPeriods: '',
  partnerEmployerNames: '',
  partnerEmployerCountries: '',
  partnerEmployerWorkLocations: '',
  partnerEmployerPeriods: '',
  hasCommuteExpenses: '',
  hasBusinessIncome: '',
  businessNames: '',
  businessLegalForms: '',
  businessKvkNumbers: '',
  businessStartDates: '',
  businessHours1225: '',
  selfEmployedDeductionHistory: '',
  wasNotEntrepreneur: '',
  hadStartupYears: '',
  aovPremium: '',
  businessSpecialItems: '',
  partnerBusinessNames: '',
  partnerBusinessLegalForms: '',
  partnerBusinessKvkNumbers: '',
  partnerBusinessStartDates: '',
  partnerBusinessHours1225: '',
  partnerSelfEmployedDeductionHistory: '',
  partnerWasNotEntrepreneur: '',
  partnerHadStartupYears: '',
  partnerAovPremium: '',
  partnerBusinessSpecialItems: '',
  hasFreelanceIncome: '',
  freelanceDetails: '',
  partnerFreelanceDetails: '',
  hasSocialBenefits: '',
  benefitsDetails: '',
  partnerBenefitsDetails: '',
  hasPensionIncome: '',
  pensionDetails: '',
  pensionStartedIn2024: '',
  partnerPensionDetails: '',
  partnerPensionStartedIn2024: '',
  receivesAlimony: '',
  alimonyAmount: '',
  partnerAlimonyAmount: '',
  hasSubstantialInterest: '',
  dividendReceived: '',
  sharesSold: '',
  partnerDividendReceived: '',
  partnerSharesSold: '',
  hasAssets: '',
  savingsBalance: '',
  investments: '',
  realEstate: '',
  otherAssets: '',
  debts: '',
  partnerSavingsBalance: '',
  partnerInvestments: '',
  partnerRealEstate: '',
  partnerOtherAssets: '',
  partnerDebts: '',
  hasOwnHome: '',
  homeAddress: '',
  homeWozValue: '',
  homeMortgageInterest: '',
  homeBoughtOrSold: '',
  partnerHomeAddress: '',
  partnerHomeWozValue: '',
  partnerHomeMortgageInterest: '',
  partnerHomeBoughtOrSold: '',
  mortgageDistribution: '',
  alimonyPaid: '',
  partnerAlimonyPaid: '',
  medicalExpenses: '',
  partnerMedicalExpenses: '',
  donations: '',
  partnerDonations: '',
  annuityPremiums: '',
  partnerAnnuityPremiums: '',
  otherDeductions: '',
  partnerOtherDeductions: '',
  provisionalAssessment: '',
  partnerProvisionalAssessment: '',
  additionalRemarks: '',
  truthfulDeclaration: '',
};
